version: "3"
services:
  varnish:
    build:
      context: ./varnish
    environment:
      - VIRTUAL_HOST=magento2.docker
      - VIRTUAL_PORT=8000
      - HTTPS_METHOD=noredirect
    ports:
      - "8005:8005"
    links:
      - nginx

  nginx:
    build:
      context: ./nginx
    ports:
      - 80
    links:
      - fpm
      - db
      - redis:cache
    volumes:
      - ./magento:/var/www/magento
    env_file:
      - ./global.env

  fpm:
    hostname: fpm.magento2.docker
    build:
      context: ${PHP_VERSION}-fpm
    ports:
      - 9000
    links:
      - db
    volumes:
      - ./magento:/var/www/magento
    env_file:
      - ./global.env

  db:
    image: mariadb:${MARIADB_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./src/mariadb_data1:/var/lib/mysql
      - ./src/mariadb_log1:/var/log/mysql
    ports:
      - 3306:3306

  cli:
    hostname: cli.magento2.docker
    build:
      context: ./${PHP_VERSION}-cli
    links:
      - db
    volumes:
      - ~/.composer/cache:/root/.composer/cache
    volumes:
      - ./magento:/var/www/magento
    env_file:
      - ./global.env
      - ./composer.env
    environment:
      - M2SETUP_INSTALL_DB=true
      - M2SETUP_DB_HOST=db
      - M2SETUP_DB_NAME=magento
      - M2SETUP_DB_USER=magento
      - M2SETUP_DB_PASSWORD=magento
      - M2SETUP_BASE_URL=http://magento2.docker/
      # - M2SETUP_SECURE_BASE_URL=https://magento2.docker/
      - M2SETUP_BACKEND_FRONTNAME=admin
      - M2SETUP_ADMIN_FIRSTNAME=Admin
      - M2SETUP_ADMIN_LASTNAME=User
      - M2SETUP_ADMIN_EMAIL=marouan.ben.mansour@gmail.com
      - M2SETUP_ADMIN_USER=admin
      - M2SETUP_ADMIN_PASSWORD=password1
      - M2SETUP_VERSION=2.4.*
      # - M2SETUP_USE_SAMPLE_DATA=true

  cron:
    build:
      context: ./${PHP_VERSION}-cli
    hostname: magento2-cron.docker
    command: run-cron
    env_file:
      - ./global.env    
    environment:
      - ENABLE_SENDMAIL=true
    volumes:
      - ./magento:/var/www/magento
    links:
      - db

  es:
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    environment:
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - cluster.initial_master_nodes=elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./src/es_data1:/usr/share/elasticsearch/data
      - ./src/es_log1:/var/log/elasticsearch

  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - 15672:15672
      - 5672:5672

  redis:
    image: redis:${REDIS_VERSION}
    restart: on-failure:5
    volumes:
      - ./src/redis_data1:/data
    expose:
      - 6379

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    links:
      - db:db
    ports:
      - "8080:80"
    environment:
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      PMA_HOST: db
    depends_on:
      - db

  mailcatcher:
    build: ./mailcatcher/docker
    ports:
      - 6009:1080
    labels:
      container_group: mail